config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'students#index'

  #REPORTS
  get 'employees/all' => 'employees#all'  
  get 'students/all' => 'students#all'  
  get 'enrollments/status' => 'enrollments#status'
  get 'enrollments/female' => 'enrollments#female'
  get 'enrollments/male' => 'enrollments#male'
  get 'enrollments/repeat' => 'enrollments#repeat'
  get 'enrollments/valera' => 'enrollments#valera'
  get 'enrollments/other_municipalities' => 'enrollments#other_municipalities'


  get 'school_periods/change_school_period/:id' => "school_periods#change_school_period", as: :change_school_period
  get 'representatives/search' => "representatives#search"
  get 'employees/search' => "employees#search"
  get 'students/search' => "students#search"


  #JSON 
  get 'school_years', to: 'school_years#index'
  get 'school_years/:id', to: 'school_years#show'
  get 'parishes', to: 'parishes#index'
  get 'parishes/:id', to: 'parishes#show'
  get 'parishes/municipality/:id', to: 'parishes#by_municipality'
  get 'subjects/year/:id', to: 'subjects#by_year'
  get 'sections/year/:id', to: 'sections#by_year'
  
  #PDF
  get 'enrollments/:id/certificate_of_study', to: 'enrollments#certificate_of_study'
  get 'teachers/:id/payroll', to: 'teachers#payroll'
  get 'sections/:id/payroll', to: 'sections#payroll'

  resources :notes
  resources :enrollments
  resources :teachers
  resources :sections
  resources :administratives
  resources :students
  resources :laborers
  resources :employees
  resources :representatives
  resources :subjects
  resources :school_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :type_id
    belongs_to :parish
    belongs_to :workstation
    has_many :laborers
    has_many :administratives
    has_many :teachers
    has_many :sections

    enum gender: [:Masculino, :Femenino ]

    validates :id_number, presence: { message: '"El numero de identidad del empleado no puede quedar vacio"'},
    numericality: { only_integer: true, message: '"El numero de identidad del empleado debe de ser numerico"'},
    uniqueness: { scope: :type_id, message: '"El numero y tipo de identidad del empleado ya fue registrada"' }
    validates :name, presence: { message: '"El nombre del empleado no puede quedar vacio"'},
    length: { in: 3..30 , message: '"El nombre del empleado no puede ser menor a (3) ni mayor a (30) caracteres"'}
    validates :last_name, presence: { message: '"El apellido del empleado no puede quedar vacio"'},
    length: { in: 3..30 , message: '"El apellido del empleado no puede ser menor a (3) ni mayor a (30) caracteres"'}
    validates :gender, presence: { message: '"El sexo del empleado no puede quedar vacio"'}
    validates :direction, presence: { message: '"El dirección del empleado no puede quedar vacio"'}
    validates :date_of_birth, inclusion: { in: (Date.new(1900,1,1)..Date.today-10.years), message: "\"La fecha de nacimiento no puede ser mayor de #{Date.today-10.years} ni menor de #{Date.new(1900,1,1)}\"" }

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :variables_for_create_and_update, only: [:create, :update]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.last(5).reverse
    @type_ids = TypeId.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @type_ids = TypeId.all
    @municipalities = Municipality.all().order('name ASC')
    @parishes = Municipality.find(20).parishes.order('name ASC')
  end

    # GET /employees/search?
    def search
      @employee = Employee.find_by(type_id: params[:type_id], id_number: params[:number_id])
      if @employee === nil
        redirect_to employees_url, alert: 'No existe representante registrado con ese numero de identidad.' 
      else
        redirect_to @employee
      end
    end
    
  # GET /employees/1/edit
  def edit
    @type_ids = TypeId.all
    @municipalities = Municipality.all().order('name ASC')
    @parishes = Municipality.find(@employee.parish.municipality.id).parishes.order('name ASC')
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def all
    @employees = Employee.all.last(10).reverse
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:type_id_id, :id_number, :name, :last_name, :date_of_birth, :gender, :parish_id, :direction, :workstation_id,)
    end

    def variables_for_create_and_update
      @type_ids = TypeId.all
      @municipalities = Municipality.all().order('name ASC')
      @parishes = Parish.all()
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_administrative.html.erb
<section class="table-primary">
<div class="container">
<table class="u-full-width">
  <h1>Carga laboral administrativa</h1>
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Turno</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% if administrative == nil %>
      <tr>
        <td colspan="8">No has registrado ninguna carga administrativa</td>
      </tr>
    <% else %>
      <tr>
        <td><%= administrative.description %></td>
        <td><%= administrative.working_time %></td>
        <td><%= link_to 'Mostrar', administrative %></td>
      </tr>
    <% end %>

  </tbody>
</table>
</div>
</section>

app/views/employees/_employee.html.erb
<section class="table-primary">
<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Nacimiento</th>
      <th>Genero</th>
      <th>Cargo</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% if employees.count == 0 %>
      <tr>
        <td colspan="8">No has registrado ningun empleado</td>
      </tr>
    <% else %>
    <% employees.each do |employee| %>
      <tr>
        <td><%= employee.type_id.name %> - <%= employee.id_number %></td>
        <td><%= employee.name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.workstation.name %>
        <td><%= link_to 'Mostrar', employee %></td>
        <td><%= link_to 'Editar', edit_employee_path(employee) %></td>
        <td><%= link_to 'Eliminar', employee, method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<hr>
<%= link_to 'Nuevo', new_employee_path, class: 'button button-primary' %>
</section>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true, class: :form_form, id: :form_employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="alert alert-error margin-bottom">
      <p><strong><%= pluralize(employee.errors.count, "Error / Errores") %></strong> Prohibieron que este empleado fuera guardado:</p>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field six columns">
      <%= form.label :type_id_id, 'Tipo de identidad' %>
      <%= form.collection_select(:type_id_id, type_ids, "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>

    </div>
    <div class="field six columns">
      <%= form.label :id_number, 'Numero de identidad' %>
      <%= form.number_field :id_number, class: 'u-full-width' %>
    </div>
  </div>
  
  <div class="row">
    <div class="field six columns">
      <%= form.label :name, 'Nombre' %>
      <%= form.text_field :name, class: 'u-full-width' %>
    </div>

    <div class="field six columns">
      <%= form.label :last_name, 'Apellido'%>
      <%= form.text_field :last_name, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="field six columns">
      <%= form.label :date_of_birth, 'Nacimiento' %>
      <%= form.date_field :date_of_birth, class: 'u-full-width' %>
    </div>
    <div class="field six columns">
      <div class="row">
        <div class="six columns">
          <%= form.radio_button(:gender, "Masculino") %>
          <%= label_tag(:gender_male,   "Masculino") %>
        </div>
        <div class="six columns">
          <%= form.radio_button(:gender, "Femenino") %>
          <%= label_tag(:gender_female, "Femenino") %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="field six columns">
      <%= form.label :type_id_id, 'Municipio' %>
      <select name="municipality" class="u-full-width" id="municipality">
        <option value="">- Seleccione -</option>
        <% municipalities.each do |municipality| %>
          <% if parishes[0].municipality.id == municipality.id %>
            <option value="<%= municipality.id %>" selected><%= municipality.name %></option>
          <% else %>
            <option value="<%= municipality.id %>"><%= municipality.name %></option>
          <% end %>
        <% end %>
      </select>    
    </div>
    <div class="field six columns">
      <%= form.label :school_years_id, 'Parroquia'%>
      <%= form.collection_select(:parish_id, parishes,"id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
  </div>
  <div class="field">
    <%= form.label :direction, 'Dirección'%>
    <%= form.text_area :direction, class: 'u-full-width' %>
  </div>

  <div class="actions">
    <hr>
    <div class="field">
      <%= form.label :workstation_id, 'Cargo de trabajo'%>
      <%= form.collection_select(:workstation_id, Workstation.all(),"id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <%= form.submit 'guardar', id: :button, class: 'button-primary' %>
  </div>
<% end %>

app/views/employees/_laborer.html.erb
<section class="table-primary">
<div class="container">
<table class="u-full-width">
  <h1>Carga laboral obrera</h1>
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Turno</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% if laborer == nil %>
      <tr>
        <td colspan="8">No has registrado ninguna carga laboral</td>
      </tr>
    <% else %>
      <tr>
        <td><%= laborer.description %></td>
        <td><%= laborer.working_time %></td>
        <td><%= link_to 'Mostrar', laborer %></td>
      </tr>
    <% end %>

  </tbody>
</table>
</div>
</section>

app/views/employees/_teacher.html.erb
<section class="table-primary">
<div class="container">
<table class="u-full-width">
  <h1>Carga laboral educativa</h1>
  <thead>
    <tr>
      <th>Turno</th>
      <th>Asignatura</th>
      <th>Año</th>
      <th>Sección</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% if teachers.count == 0 %>
      <tr>
        <td colspan="8">No has registrado ninguna carga laboral</td>
      </tr>
    <% else %>
    <% teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.working_time %></td>
        <td><%= teacher.subject.name %></td>
        <td><%= teacher.section.school_year.name %></td>
        <td><%= teacher.section.name %></td>
        <td><%= link_to 'Mostrar', teacher %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
</section>

app/views/employees/all.html.erb
<div class="container">
<h1>Todos los empleados</h1>

<%= render 'employee', {employees: @employees} %>

<%= link_to 'Volver',  employees_path %>
</div>

app/views/employees/edit.html.erb
<div class="container">
<h1>Editar empleado</h1>

<%= render 'form', {employee: @employee, type_ids: @type_ids, municipalities: @municipalities, parishes: @parishes} %>

<%= link_to 'Mostrar', @employee %> |
<%= link_to 'Volver',  employees_path %>
</div>

app/views/employees/index.html.erb
<section class="search-form">
<div class="container">
  <div class="container">
    <form action="/employees/search" method="GET">
      <div class="row">
          <div class="six columns">
            <label for="store">Tipo de identidad</label>
            <select name="type_id" class="u-full-width">
              <option value="">- Seleccione -</option>
              <% @type_ids.each do |type_id| %>
                <% if type_id.id == 1 %>
                  <option value="<%= type_id.id %>" selected><%=type_id.name %></option>
                <% else %>
                  <option value="<%= type_id.id %>"><%= type_id.name%></option>
                <% end %>
              <% end %>
            </select>            
          </div>
          <div class="six columns">   
            <label for="store">Numero de identidad</label>
            <input type="number" name="number_id" class="u-full-width">
          </div>
      </div>
      <br>
      <button type="submit" class="u-full-width button button-primary">Buscar</button>   
  </div>
</div>
</section>
<section class="area-especial">
    <h1>Empleados</h1>
    <div class="container area-punteado">
      <div class="row ">
          <div class="nine columns">
            <h4>Carga laboral</h4>
            <p> Para agregar una carga laboral en este período escolar, primero deberas agregar al empleado.</p>
          </div>
          <div class="three columns buttons">
            <%= link_to 'AGREGAR', new_employee_path, class: 'button-blue' %>
            <%= link_to 'ADMINISTRATIVO', new_administrative_path, class: 'button-yellow' %>
            <%= link_to 'DOCENTE', new_teacher_path, class: 'button-yellow' %>
            <%= link_to 'OBRERO', new_laborer_path, class: 'button-yellow' %>
          </div>
      </div>
    </div>
</section>

<section class="area-reportes">
    <div class="container">
        <div class="reportes">
          <!-- Variable de estudiantes inscritos -->
            <a href="/employees/all" class="reporte reporte-blue">
                <h5><%= Employee.all.count %></h5>
                <p>Registrados</p>
            </a>
            <a href="/administratives" class="reporte reporte-yellow">
                <h5><%= Administrative.where(school_period_id: session[:school_period]).count %></h5>
                <p>Cargas administrativas</p>
            </a>
            <a href="/teachers" class="reporte reporte-yellow">
                <h5><%= Teacher.where(section: Section.where(school_period_id: session[:school_period])).count %></h5>
                <p>Cargas academicas</p>
            </a>
            <a href="/laborers" class="reporte reporte-yellow">
                <h5><%= Laborer.where(school_period_id: session[:school_period]).count %></h5>
                <p>Cargas obreras</p>
            </a>
        </div>
    </div>
</section>

app/views/employees/new.html.erb
<div class="container">
<h1>Agregar empleado</h1>

<%= render 'form', {employee: @employee, type_ids: @type_ids, municipalities: @municipalities, parishes: @parishes} %>

<%= link_to 'Volver', employees_path %>
</div>

app/views/employees/show.html.erb
  <div class="container">
    <section class="show">
      <ul>
      <div class="row">
        <div class="six columns">
          <li><strong>Tipo de documento</strong></li>
          <p><%= @employee.type_id.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Numero de documento</strong></li>
          <p><%= @employee.id_number %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Nombres</strong></li>
          <p><%= @employee.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Apellidos</strong></li>
          <p><%= @employee.last_name %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Nacimiento</strong></li>
          <p><%= @employee.date_of_birth %></p>
        </div>
        <div class="six columns">
          <li><strong>Sexo</strong></li>
          <p><%= @employee.gender %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Municipio de Residencia</strong></li>
          <p><%= @employee.parish.municipality.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Parroquia de Residencia</strong></li>
          <p><%= @employee.parish.name %></p>
        </div>
      </div>
      <div class="row">
          <li><strong>Dirección de Residencia</strong></li>
          <p><%= @employee.direction %></p>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Registrado</strong></li>
          <%= @employee.created_at %>
        </div>
        <div class="six columns">
          <li><strong>Actualizado</strong></li>
          <p><%= @employee.updated_at %></p>
        </div>
      </div>
      </ul>
      <hr>
      <%= link_to 'Editar', edit_employee_path(@employee) %> |
      <%= link_to 'Volver', employees_path %>
    </section>
</div>

<% 
case @employee.workstation.id # a_variable is the variable we want to compare
when 1 %>
  <%= render 'teacher', {teachers: Teacher.where(section_id: Section.where(school_period_id: session[:school_period]), employee: @employee.id)} %> 
<%
when 2 %>   
  <%= render 'administrative', {administrative: Administrative.find_by(school_period_id: session[:school_period], employee: @employee.id)} %> 
<%
when 3%>
  <%= render 'laborer', {laborer: Laborer.find_by(school_period_id: session[:school_period], employee: @employee.id)} %> 
<%
else
  
end
%>