config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'students#index'

  #REPORTS
  get 'employees/all' => 'employees#all'  
  get 'students/all' => 'students#all'  
  get 'enrollments/status' => 'enrollments#status'
  get 'enrollments/female' => 'enrollments#female'
  get 'enrollments/male' => 'enrollments#male'
  get 'enrollments/repeat' => 'enrollments#repeat'
  get 'enrollments/valera' => 'enrollments#valera'
  get 'enrollments/other_municipalities' => 'enrollments#other_municipalities'


  get 'school_periods/change_school_period/:id' => "school_periods#change_school_period", as: :change_school_period
  get 'representatives/search' => "representatives#search"
  get 'employees/search' => "employees#search"
  get 'students/search' => "students#search"


  #JSON 
  get 'school_years', to: 'school_years#index'
  get 'school_years/:id', to: 'school_years#show'
  get 'parishes', to: 'parishes#index'
  get 'parishes/:id', to: 'parishes#show'
  get 'parishes/municipality/:id', to: 'parishes#by_municipality'
  get 'subjects/year/:id', to: 'subjects#by_year'
  get 'sections/year/:id', to: 'sections#by_year'
  
  #PDF
  get 'enrollments/:id/certificate_of_study', to: 'enrollments#certificate_of_study'
  get 'teachers/:id/payroll', to: 'teachers#payroll'
  get 'sections/:id/payroll', to: 'sections#payroll'

  resources :notes
  resources :enrollments
  resources :teachers
  resources :sections
  resources :administratives
  resources :students
  resources :laborers
  resources :employees
  resources :representatives
  resources :subjects
  resources :school_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/representative.rb
class Representative < ApplicationRecord
    belongs_to :type_id
    belongs_to :parish
    has_many :enrollments

    enum gender: [:Masculino, :Femenino ]
    

    validates :id_number, presence: { message: '"El numero de identidad del representante no puede quedar vacio"'},
    numericality: { only_integer: true, message: '"El numero de identidad del representante debe de ser numerico"'},
    uniqueness: { scope: :type_id, message: '"El numero y tipo de identidad del representante ya fue registrada"' }
    validates :name, presence: { message: '"El nombre del representante no puede quedar vacio"'},
    length: { in: 3..30 , message: '"El nombre del representante no puede ser menor a (3) ni mayor a (30) caracteres"'}
    validates :last_name, presence: { message: '"El apellido del representante no puede quedar vacio"'},
    length: { in: 3..30 , message: '"El apellido del representante no puede ser menor a (3) ni mayor a (30) caracteres"'}
    validates :gender, presence: { message: '"El sexo del representante no puede quedar vacio"'}
    validates :direction, presence: { message: '"El dirección del representante no puede quedar vacio"'}
    validates :date_of_birth, inclusion: { in: (Date.new(1900,1,1)..Date.today-10.years), message: "\"La fecha de nacimiento no puede ser mayor de #{Date.today-10.years} ni menor de #{Date.new(1900,1,1)}\"" }

end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_representative, only: [:show, :edit, :update, :destroy]
  before_action :variables_for_create_and_update, only: [:create, :update]

  # GET /representatives
  # GET /representatives.json
  def index
    @representatives = Representative.all.last(5).reverse
  end

  # GET /representatives/1
  # GET /representatives/1.json
  def show
  end

  # GET /representatives/search?
  def search
    @representative = Representative.find_by(type_id: params[:type_id], id_number: params[:number_id])
    if @representative === nil
      redirect_to representatives_url, alert: 'No existe representante registrado con ese numero de identidad.' 
    else
      redirect_to @representative
    end
  end


  # GET /representatives/new
  def new
    @representative = Representative.new
    @municipalities = Municipality.all().order('name ASC')
    @parishes = Municipality.find(20).parishes.order('name ASC')
  end

  # GET /representatives/1/edit
  def edit
    @municipalities = Municipality.all().order('name ASC')
    @parishes = Municipality.find(@representative.parish.municipality.id).parishes.order('name ASC')
  end

  # POST /representatives
  # POST /representatives.json
  def create
    @representative = Representative.new(representative_params)
    

    respond_to do |format|
      if @representative.save
        format.html { redirect_to @representative, notice: 'Representante fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @representative }
      else
        format.html { render :new }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representatives/1
  # PATCH/PUT /representatives/1.json
  def update
    respond_to do |format|
      if @representative.update(representative_params)
        format.html { redirect_to @representative, notice: 'Representante fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @representative }
      else
        format.html { render :edit }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representatives/1
  # DELETE /representatives/1.json
  def destroy
    @representative.destroy
    respond_to do |format|
      format.html { redirect_to representatives_url, notice: 'Representative fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representative
      @representative = Representative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representative_params
      params.require(:representative).permit(:type_id_id, :id_number, :name, :last_name, :date_of_birth, :gender, :parish_id, :direction)
    end

    def variables_for_create_and_update
      @municipalities = Municipality.all().order('name ASC')
      @parishes = Parish.all()
    end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
end

app/views/representatives/_form.html.erb
<%= form_with(model: representative, local: true, class: :form_form, id: :form_representative) do |form| %>
  <% if representative.errors.any? %>
    <div id="error_explanation" class="alert alert-error margin-bottom">
      <p><strong><%= pluralize(representative.errors.count, "Error / Errores") %></strong> Prohibieron que este representante fuera guardado:</p>
      <ul>
        <% representative.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field six columns">
      <%= form.label :type_id_id, 'Tipo de identidad' %>
      <%= form.collection_select(:type_id_id, TypeId.all(), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>

    </div>
    <div class="field six columns">
      <%= form.label :id_number, 'Numero de identidad' %>
      <%= form.number_field :id_number, class: 'u-full-width' %>
    </div>
  </div>
  
  <div class="row">
    <div class="field six columns">
      <%= form.label :name, 'Nombre' %>
      <%= form.text_field :name, class: 'u-full-width' %>
    </div>

    <div class="field six columns">
      <%= form.label :last_name, 'Apellido'%>
      <%= form.text_field :last_name, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="field six columns">
      <%= form.label :date_of_birth, 'Nacimiento' %>
      <%= form.date_field :date_of_birth, class: 'u-full-width' %>
    </div>
    <div class="field six columns">
      <div class="row">
        <div class="six columns">
          <%= form.radio_button(:gender, "Masculino") %>
          <%= label_tag(:gender_male,   "Masculino") %>
        </div>
        <div class="six columns">
          <%= form.radio_button(:gender, "Femenino") %>
          <%= label_tag(:gender_female, "Femenino") %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="field six columns">
      <%= form.label :type_id_id, 'Municipio' %>
      <select name="municipality" class="u-full-width" id="municipality">
        <option value="">- Seleccione -</option>
        <% municipalities.each do |municipality| %>
          <% if parishes[0].municipality.id == municipality.id %>
            <option value="<%= municipality.id %>" selected><%= municipality.name %></option>
          <% else %>
            <option value="<%= municipality.id %>"><%= municipality.name %></option>
          <% end %>
        <% end %>
      </select>    
    </div>
    <div class="field six columns">
      <%= form.label :school_years_id, 'Parroquia'%>
      <%= form.collection_select(:parish_id, parishes,"id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
  </div>
  <div class="field">
    <%= form.label :direction, 'Dirección'%>
    <%= form.text_area :direction, class: 'u-full-width' %>
  </div>

  <div class="actions">
    <hr>
    <%= form.submit 'guardar', id: :button, class: 'button-primary' %>
  </div>
<% end %>

app/views/representatives/edit.html.erb
<div class="container">
<h1 class="margin-top">Editar representante</h1>

<%= render 'form', {representative: @representative, type_ids: @type_ids, municipalities: @municipalities, parishes: @parishes} %>

<%= link_to 'Mostrar', @representative %> |
<%= link_to 'Volver',  representatives_path %>
</div>

app/views/representatives/index.html.erb
<section class="search-form">
<div class="container">
  <div class="container">
    <form action="/representatives/search" method="GET">
      <div class="row">
          <div class="six columns">
            <label for="store">Tipo de identidad</label>
            <select name="type_id" class="u-full-width">
              <option value="">- Seleccione -</option>
              <% TypeId.all.each do |type_id| %>
                <% if type_id.id == 1 %>
                  <option value="<%= type_id.id %>" selected><%=type_id.name %></option>
                <% else %>
                  <option value="<%= type_id.id %>"><%= type_id.name%></option>
                <% end %>
              <% end %>
            </select>            
          </div>
          <div class="six columns">   
            <label for="store">Numero de identidad</label>
            <input type="number" name="number_id" class="u-full-width">
          </div>
      </div>
      <br>
      <button type="submit" class="u-full-width button button-primary">Buscar</button>   
  </div>
</div>
</section>
<section class="area-especial">
    <h1>Representantes</h1>
    <div class="container area-punteado">
      <div class="row ">
          <div class="nine columns">
            <h4>Inscripciones</h4>
            <p> Para inscribir a un estudiante en este período escolar, deberas agregar al representante primero (Opcional).</p>
          </div>
          <div class="three columns buttons">
            <%= link_to 'AGREGAR', new_representative_path, class: 'button-blue' %>
            <%= link_to 'INSCRIBIR', new_enrollment_path, class: 'button-yellow' %>
          </div>
      </div>
    </div>
</section>

app/views/representatives/new.html.erb
<div class="container">
<h1 class="margin-top">Agregar representante</h1>

<%= render 'form', {representative: @representative, type_ids: @type_ids, municipalities: @municipalities, parishes: @parishes} %>

<%= link_to 'Volver', representatives_path %>
</div>

app/views/representatives/show.html.erb
  <div class="container">
    <section class="show">
      <ul>
      <div class="row">
        <div class="six columns">
          <li><strong>Tipo de documento</strong></li>
          <p><%= @representative.type_id.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Numero de documento</strong></li>
          <p><%= @representative.id_number %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Nombres</strong></li>
          <p><%= @representative.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Apellidos</strong></li>
          <p><%= @representative.last_name %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Nacimiento</strong></li>
          <p><%= @representative.date_of_birth %></p>
        </div>
        <div class="six columns">
          <li><strong>Sexo</strong></li>
          <p><%= @representative.gender %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Municipio de Residencia</strong></li>
          <p><%= @representative.parish.municipality.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Parroquia de Residencia</strong></li>
          <p><%= @representative.parish.name %></p>
        </div>
      </div>
      <div class="row">
          <li><strong>Dirección de Residencia</strong></li>
          <p><%= @representative.direction %></p>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Registrado</strong></li>
          <%= @representative.created_at %>
        </div>
        <div class="six columns">
          <li><strong>Actualizado</strong></li>
          <p><%= @representative.updated_at %></p>
        </div>
      </div>
      </ul>
      <hr>
      <%= link_to 'Editar', edit_representative_path(@representative) %> |
      <%= link_to 'Volver', representatives_path %>
    </section>

</div>

<section class="table-primary">
<div class="container">
<table class="u-full-width">
  <h1>Estudiantes inscritos</h1>
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Genero</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% enrollments = @representative.enrollments %>
    <% if enrollments.count == 0 %>
      <tr>
        <td colspan="8">No has inscrito ningun estudiante</td>
      </tr>
    <% else %>
    <% enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.student.type_id.name %> - <%= enrollment.student.id_number %></td>
        <td><%= enrollment.student.name %></td>
        <td><%= enrollment.student.last_name %></td>
        <td><%= enrollment.student.gender %></td>
        <td><%= link_to 'Mostrar', enrollment.student %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
</section>