config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'students#index'

  #REPORTS
  get 'employees/all' => 'employees#all'  
  get 'students/all' => 'students#all'  
  get 'enrollments/status' => 'enrollments#status'
  get 'enrollments/female' => 'enrollments#female'
  get 'enrollments/male' => 'enrollments#male'
  get 'enrollments/repeat' => 'enrollments#repeat'
  get 'enrollments/valera' => 'enrollments#valera'
  get 'enrollments/other_municipalities' => 'enrollments#other_municipalities'


  get 'school_periods/change_school_period/:id' => "school_periods#change_school_period", as: :change_school_period
  get 'representatives/search' => "representatives#search"
  get 'employees/search' => "employees#search"
  get 'students/search' => "students#search"


  #JSON 
  get 'school_years', to: 'school_years#index'
  get 'school_years/:id', to: 'school_years#show'
  get 'parishes', to: 'parishes#index'
  get 'parishes/:id', to: 'parishes#show'
  get 'parishes/municipality/:id', to: 'parishes#by_municipality'
  get 'subjects/year/:id', to: 'subjects#by_year'
  get 'sections/year/:id', to: 'sections#by_year'
  
  #PDF
  get 'enrollments/:id/certificate_of_study', to: 'enrollments#certificate_of_study'
  get 'teachers/:id/payroll', to: 'teachers#payroll'
  get 'sections/:id/payroll', to: 'sections#payroll'

  resources :notes
  resources :enrollments
  resources :teachers
  resources :sections
  resources :administratives
  resources :students
  resources :laborers
  resources :employees
  resources :representatives
  resources :subjects
  resources :school_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_nav_primary.html.erb
<nav class="primary">
    <div class="logo">
        <a href="#">
            <%= image_tag("logo.png", :alt => "Logo del LBRR") %>
            <p> L.B Rafael Rangel</p>
        </a>
    </div>
    <div class="derecha">
        <%= link_to 'Periodo escolar', school_periods_path %>
        <%= link_to 'Salir', destroy_user_session_path, class: 'button-red' %>
    </div>
</nav>

app/views/partials/_nav_secondary.html.erb
<nav class="secondary">
<ul>
    <li><%= link_to 'Estudiantes', students_path %></li>

    <li><%= link_to 'Representantes', representatives_path %></li>
    <li><%= link_to 'Empleados', employees_path %></li>


    <li><%= link_to 'Secciones', sections_path %></li>
    <li><%= link_to 'Asignaturas', subjects_path %></li>
    <li><%= link_to 'Notas', notes_path %></li>


    <% #Validar esto
    #<li><a href="/user">Usuarios</a></li>
    %>
    
</ul>
</nav>