config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'students#index'

  #REPORTS
  get 'employees/all' => 'employees#all'  
  get 'students/all' => 'students#all'  
  get 'enrollments/status' => 'enrollments#status'
  get 'enrollments/female' => 'enrollments#female'
  get 'enrollments/male' => 'enrollments#male'
  get 'enrollments/repeat' => 'enrollments#repeat'
  get 'enrollments/valera' => 'enrollments#valera'
  get 'enrollments/other_municipalities' => 'enrollments#other_municipalities'


  get 'school_periods/change_school_period/:id' => "school_periods#change_school_period", as: :change_school_period
  get 'representatives/search' => "representatives#search"
  get 'employees/search' => "employees#search"
  get 'students/search' => "students#search"


  #JSON 
  get 'school_years', to: 'school_years#index'
  get 'school_years/:id', to: 'school_years#show'
  get 'parishes', to: 'parishes#index'
  get 'parishes/:id', to: 'parishes#show'
  get 'parishes/municipality/:id', to: 'parishes#by_municipality'
  get 'subjects/year/:id', to: 'subjects#by_year'
  get 'sections/year/:id', to: 'sections#by_year'
  
  #PDF
  get 'enrollments/:id/certificate_of_study', to: 'enrollments#certificate_of_study'
  get 'teachers/:id/payroll', to: 'teachers#payroll'
  get 'sections/:id/payroll', to: 'sections#payroll'

  resources :notes
  resources :enrollments
  resources :teachers
  resources :sections
  resources :administratives
  resources :students
  resources :laborers
  resources :employees
  resources :representatives
  resources :subjects
  resources :school_periods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :school_year
  belongs_to :section, required: false
  belongs_to :student
  belongs_to :school_period
  belongs_to :representative, required: false
  has_many :notes

  enum status: [:Activo, :Retirado]

  validates_uniqueness_of :student_id, scope: :school_period, message: '"Este estudiante ya fue inscrito"'

  before_validation :generate_student_id
  before_validation :generate_representative_id

  
  attr_accessor :type_id_id
  attr_accessor :id_number
  attr_accessor :representative_type_id_id
  attr_accessor :representative_id_number 

  def generate_student_id
    student_search = Student.find_by(type_id: type_id_id, id_number: id_number)
    if student_search != nil
      self.student_id = student_search.id
    end
  end    
  def generate_representative_id
    representative_search = Representative.find_by(type_id: representative_type_id_id, id_number: representative_id_number )
    if representative_search != nil
      self.representative_id = representative_search.id
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy, :certificate_of_study]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.where(school_period_id: session[:school_period]).last(5).reverse
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.school_period_id = session[:school_period]
    @enrollment.status = 0
    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def certificate_of_study
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/certificate_of_study', pdf: 'Certificate_of_study'}
    end
  end

  def status
    @enrollments = Enrollment.where(school_period_id: session[:school_period], status: 1)
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Retirados'}
    end
  end

  def female
    @enrollments = Enrollment.where(school_period_id: session[:school_period], student: Student.where(gender: 1))
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Femenino'}
    end
  end

  def male
    @enrollments = Enrollment.where(school_period_id: session[:school_period], student: Student.where(gender: 0))
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Masculino'}
    end  
  end

  def repeat
    @enrollments = Enrollment.where(school_period_id: session[:school_period], repeat: 1)
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Repeat'}
    end  
  end

  def valera
    @enrollments = Enrollment.where(school_period_id: session[:school_period], student: Student.where(parish: Parish.where(municipality_id: 20)))
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Valera'}
    end  
  end

  def other_municipalities
    @enrollments = Enrollment.where(school_period_id: session[:school_period], student: Student.where(parish: Parish.where.not(municipality_id: 20)))
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'enrollments/payroll', pdf: 'Otros_Municipios'}
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:repeat, :status, :representative_type_id_id, :representative_id_number,:type_id_id, :id_number, :school_year_id, :section_id, :student_id, :school_period_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<tr>
<td><%= enrollment.student.type_id.name %> - <%= enrollment.student.id_number %></td>
<td><%= enrollment.student.name %></td>
<td><%= enrollment.student.last_name %></td>
<% if enrollment.representative == nil %>
    <td>¿?</td>
<% else %>
    <td><%= link_to "#{enrollment.representative.type_id.name} - #{enrollment.representative.id_number}", enrollment.representative %></td>
<% end %>
<td><%= enrollment.school_year.id %></td>
<% if enrollment.section == nil %>
    <td>¿?</td>
<% else %>
    <td><%= enrollment.section.name %></td>
<% end %>
<td><%= link_to 'Mostrar', enrollment %></td>
<td><%= link_to 'Editar', edit_enrollment_path(enrollment) %></td>
<td><%= link_to 'Eliminar', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true, class: :form_form, id: :form_enrollment) do |form| %>
  <% if enrollment.errors.any? %>
     <div id="error_explanation" class="alert alert-error margin-bottom">
      <p><strong><%= pluralize(enrollment.errors.count, "Error / Errores") %></strong> Prohibieron que el estudiante fuera inscrito:</p>

      <ul>
        <% enrollment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p><strong>Identidad del estudiante</strong></p>
  <div class="row">
    <div class="field six columns">
      <%= form.label :type_id_id, 'Tipo de identidad' %>
      <%= form.collection_select(:type_id_id, TypeId.all(), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <div class="field six columns">
      <%= form.label :id_number, 'Numero de identidad' %>
      <%= form.number_field :id_number, class: 'u-full-width' %>
    </div>
  </div>
  <hr>
  <p><strong>Identidad del representante</strong></p>
  <div class="row">
    <div class="field six columns">
      <%= form.label :representative_type_id_id, 'Tipo de identidad' %>
      <%= form.collection_select(:representative_type_id_id, TypeId.all(), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <div class="field six columns">
      <%= form.label :representative_id_number, 'Numero de identidad' %>
      <%= form.number_field :representative_id_number, class: 'u-full-width' %>
    </div>
  </div>

  <div class="row">
    <div class="field six columns">
      <%= form.label :school_year_id, 'Año escolar' %>
      <%= form.collection_select(:school_year_id, SchoolYear.all(), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <div class="field six columns">
      <%= form.label :section_id, 'Sección' %>
      <%= form.collection_select(:section_id, Section.where(school_year_id: 99), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
  </div>
  <div class="field">
    <%= form.label :repeat, 'Repite' %>
    <%= form.check_box :repeat %>
  </div>
  <div class="actions">
    <%= form.submit 'Guardar', id: :button, class: 'button-primary' %>
  </div>
<% end %>

app/views/enrollments/certificate_of_study.pdf.erb
<!DOCTYPE html>
<html>
<head>
	<title>Constancia de Estudio</title>
	<meta charset="utf-8">
	<style type="text/css">
		body{
			font-family: Arial;
		}

		h2, h4, p{
			text-align: center;
		}

		p.texto{
			text-align: justify;
		}

		.bloque1{
			margin-top: 10%;
			padding: 2%;
		}

		.bloque2{
			margin-top: 10%;
		}

		.imgHeader{
			width: 100%;
		}

		.img1{
			float: left;
			width: 80%;
		}

		.img2{
			float: right;
			width: 20%;
		}

		.imgGob{
			width: 100%;
		}

		.imgLogo{
			width: 60%;
			float: right;
			margin-top: 1%;
		}

	</style>
</head>
<body>
	<div class="imgHeader">
		<div class="img1">
			<%= wicked_pdf_image_tag('gob.png', :alt => "Logo del mppe", class: 'imgGob') %>
		</div>
		<div class="img2">
			<%= wicked_pdf_image_tag('logo.png', :alt => "Logo del LBRR", class: 'imgLogo') %>
		</div>
	</div>
	<hr>
	<div class="bloque1">
		<h2>Constancia de Estudio</h2>
		<p class="texto">Quien suscribe, Elizabeth Estrada Director(a) del Liceo Bolivariano "RAFAEL RANGEL" de Valera estado Trujillo, código 007917800, por medio de la presente hace constar que el(la) estudiante <b><%= (@enrollment.student.last_name).titleize %> <%= (@enrollment.student.name).titleize %></b> titular de la Cédula de identidad <%= @enrollment.student.id_number %>, cursa en este plantel <%= @enrollment.school_year.name %>° año, sección (<%= @enrollment.section.name %>) del ciclo de Educación <%= SchoolPeriod.find(session[:school_period]).name %>, durante año escolar <%= "#{SchoolPeriod.find(session[:school_period]).name} - #{SchoolPeriod.find(session[:school_period]).name + 1}"%>.</p>

		<p class="texto">Constancia que se expide en Valera en la fecha (<%= Date.today %>)</p>
	</div>
	<div class="bloque2">
		<h4>Por la Dirección</h4>
		<p>________________________</p>
		<p>Elizabeth Estrada</p>
		<p>Director(a)</p>
	</div>
</body>
</html>

app/views/enrollments/edit.html.erb
<div class="container">
<h1 class="margin-top">Editar inscripción</h1>

<%= form_with(model: @enrollment, local: true, class: :form_form) do |form| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation" class="alert alert-error margin-bottom">
      <p><strong><%= pluralize(@enrollment.errors.count, "Error / Errores") %></strong> Prohibieron que esta carga laboral administrativa fuera editada:</p>

      <ul>
        <% @enrollment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p><strong>Identidad del representante</strong></p>
  <div class="row">
    <div class="field six columns">
      <%= form.label :representative_type_id_id, 'Tipo de identidad' %>
      <%= form.collection_select(:representative_type_id_id, TypeId.all(), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <div class="field six columns">
      <%= form.label :representative_id_number, 'Numero de identidad' %>
      <%= form.number_field :representative_id_number, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="field six columns">
      <%= form.label :section_id, 'Sección' %>
      <%= form.collection_select(:section_id, Section.where(school_year_id: @enrollment.school_year.id, school_period_id: session[:school_period]).order('name ASC'), "id", "name", {include_blank: "- Seleccione -"}, {class: "u-full-width"}) %>
    </div>
    <div class="field six columns">
      <div class="row">
        <div class="four columns">
          <%= form.radio_button(:status, "Activo") %>
          <%= label_tag(:status_active,   "Activo") %>
        </div>
        <div class="four columns">
          <%= form.radio_button(:status, "Retirado") %>
          <%= label_tag(:status_inactive, "Retirado") %>
        </div>
        <div class="field four columns">
          <%= form.label :repeat, 'Repite' %>
          <%= form.check_box :repeat %>
        </div>
      </div>
  </div>
  </div>
  <div class="actions">
    <%= form.submit 'Guardar', id: :button, class: 'button-primary' %>
  </div>
<% end %>


<%= link_to 'Mostrar', @enrollment %> |
<%= link_to 'Volver',  enrollments_path %>
</div>

app/views/enrollments/female.html.erb
<div class="container">
<h1>Estudiantes - Femenino</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'female.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/index.html.erb
<div class="container">
<h1>Estudiantes inscritos</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has inscrito a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/male.html.erb
<div class="container">
<h1>Estudiantes - Masculino</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'male.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/new.html.erb
<div class="container">
<h1 class="margin-top">Inscribir estudiante</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Volver', enrollments_path %>
</div>

app/views/enrollments/other_municipalities.html.erb
<div class="container">
<h1>Estudiantes de otros municipios</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'other_municipalities.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/payroll.pdf.erb
<!DOCTYPE html>
<html>
<head>
	<title>Planilla de estudiantes inscritos</title>
	<meta charset="utf-8">
		<style type="text/css">
		body{
			font-family: Arial;
		}
		table{
			font-size: 12px;
			width: 100%;
		}

	</style>
</head>


<body>

	</br>
    <h2 align="center">Estudiantes</h2>
	<table border>
		<thead>
			<tr>
				<th>IDENTIDAD</th>
				<th>APELLIDOS Y NOMBRES</th>
				<th>SEXO</th>
                <th>FECHA DE NACIMIENTO</th>
                <th>AÑO</th>
                <th>Sección</th>
                <th>REPITE</th>
			</tr>
		</thead>
		<tbody>
			<% @enrollments.each do |enrollment| %>
				<tr>
					<td><%= enrollment.student.type_id.name %> - <%= enrollment.student.id_number %></td>
					<td><%= enrollment.student.last_name.upcase %> <%= enrollment.student.name.upcase %></td>
					<td><%= enrollment.student.gender %></td>
                    <td><%= enrollment.student.date_of_birth %></td>
                    <td><%= enrollment.school_year.name %></td>
                    <% if enrollment.section%>
                        <td><%= enrollment.section.name %></td>
                    <% else %>
                        <td>¿?</td>
                    <% end %>
                    <% if enrollment.repeat%>
                        <td>X</td>
                    <% else %>
                        <td></td>
                    <% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</body>
</html>

app/views/enrollments/repeat.html.erb
<div class="container">
<h1>Estudiantes repitientes</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'repeat.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/show.html.erb
<div class="container">
  <div class="container">
    <section class="show">
      <ul>
      <div class="row">
        <div class="six columns">
          <li><strong>Nombres</strong></li>
          <p><%= @enrollment.student.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Apellidos</strong></li>
          <p><%= @enrollment.student.last_name %></p>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Año</strong></li>
          <p><%= @enrollment.school_year.name %></p>
        </div>
        <div class="six columns">
          <li><strong>Sección</strong></li>
          <% if @enrollment.section == nil %>
          <p>¿?</p>
          <% else %>
          <p><%= @enrollment.section.name %></p>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Estado</strong></li>
          <p><%= @enrollment.status %></p>
        </div>
        <div class="six columns">
          <li><strong>Repite</strong></li>
          <% if @enrollment.repeat %>
          <p>Si</p>
          <% else %>
          <p>No</p>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <li><strong>Creada</strong></li>
          <p><%= @enrollment.created_at %></p>
        </div>
        <div class="six columns">
          <li><strong>Actualizado</strong></li>
          <p><%= @enrollment.updated_at %></p>
        </div>
      </div>
      </ul>
      <hr>
      <% if @enrollment.representative != nil %>
        <%= link_to 'Representate', @enrollment.representative %> |
      <% end %>
      <%= link_to 'Estudiante', @enrollment.student %> |
      <%= link_to 'Editar', edit_enrollment_path(@enrollment) %> |
      <%= link_to 'Volver', enrollments_path %>
    </section>
  </div>
</div>

app/views/enrollments/status.html.erb
<div class="container">
<h1>Estudiantes retirados</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'status.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>

app/views/enrollments/valera.html.erb
<div class="container">
<h1>Estudiantes de Valera</h1>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Identificación</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Representante</th>
      <th>Año</th>
      <th>Seccíon</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
  <% if @enrollments.any? %>
    <%= render @enrollments %>
  <% else %>
    <tr>
      <td>No has retirado a ningun estudiante</td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr>


<%= link_to 'Nueva inscripción', new_enrollment_path, class: 'button button-primary' %>
<%= link_to 'PDF', 'valera.pdf', class: 'button' %>
<br>
<%= link_to 'Volver',  students_path %>
</div>